#include "common/test/FakeKvApp.hh"
#include "common/test/TestHelpers.hh"
#include "common/KvalobsAccess.hh"
inline TimeSpan t_12600_20141008()
    { return TimeSpan(s2t("2014-10-05 06:00:00"), s2t("2014-10-08 06:00:00")); }
#ifdef LOAD_DECL_ONLY
void load_12600_20141008(FakeKvApp& fa);
#else // LOAD_DECL_ONLY
void load_12600_20141008(FakeKvApp& fa)
{
    fa.insertStation = 12600;
    fa.insertParam = 110;
    fa.insertType = 302;
    fa.insertData("2014-10-05 06:00:00",  -32767.0,       0.5, "0000001000001005", "hqc-m");
    fa.insertData("2014-10-06 06:00:00",  -32767.0,       1.3, "0000001000001005", "hqc-m");
    fa.insertData("2014-10-07 06:00:00",       0.1,       0.1, "0110000000000010", "");
    fa.insertData("2014-10-08 06:00:00",      12.0,      12.0, "0110000000001010", "");

    fa.insertStation = 12600;
    fa.insertParam = 110;
    fa.insertModel("2014-10-05 06:00:00",       1.1);
    fa.insertModel("2014-10-05 18:00:00",       0.4);
    fa.insertModel("2014-10-06 06:00:00",       0.3);
    fa.insertModel("2014-10-06 18:00:00",       2.5);
    fa.insertModel("2014-10-07 06:00:00",       0.6);
    fa.insertModel("2014-10-07 18:00:00",       0.6);
    fa.insertModel("2014-10-08 06:00:00",      17.7);

    fa.addStation("12600;10.679;60.953;161.0;VEA;0;1967-06-01 00:00:00");

    fa.addObsPgm("12600;110;0;1;402;0;0;0;0;0;0;0;1;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;1;1;1;1;1;1;1;1967-01-01 06:00:00;2013-03-07 06:00:00");
    fa.addObsPgm("12600;110;0;1;302;0;0;0;0;0;0;0;1;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;1;1;1;1;1;1;1;2008-09-13 00:00:00;null");

    fa.addTypes(kvalobs::kvTypes(302,"SMS meldingsformat 2",30,1080,"M","h","Nedboermelding m param SD"));
    fa.addTypes(kvalobs::kvTypes(402,"ukekort",0,38900,"M","h","etterregistrert"));

    fa.addParam(kvalobs::kvParam(105,"RR_01","Nedbør, tilvekst siste minutt","mm",0,"1 min akkumulert"));
    fa.addParam(kvalobs::kvParam(109,"RR_12","Nedbør, tilvekst siste 12 timer","mm",0,"Verdien -1 angir at nedbør ikke er observert"));
    fa.addParam(kvalobs::kvParam(110,"RR_24","Nedbør, tilvekst siste 24 timer","mm",0,"Verdien -1 angir at nedbør ikke er observert"));
    fa.addParam(kvalobs::kvParam(108,"RR_6","Nedbør, tilvekst siste 6 timer","mm",0,"Verdien -1 angir at nedbør ikke er observert"));

}
#endif // !LOAD_DECL_ONLY

// generated by '/home/alexanderb/tools/kvhqc/fetch_test_data.py' '--params' '110' '12600' '2014-10-05 06:00:00' '2014-10-08 06:00:00' on 2014-10-10T09:17:11.543976
// Local Variables:
// buffer-read-only: t
// End:
