#include "common/test/FakeKvApp.hh"
#include "common/test/TestHelpers.hh"
#include "common/KvalobsAccess.hh"
inline TimeRange t_18210_20130410()
    { return TimeRange(s2t("2013-04-01 00:00:00"), s2t("2013-04-10 10:00:00")); }
#ifdef LOAD_DECL_ONLY
void load_18210_20130410(FakeKvApp& fa, bool subscribe=true);
#else // LOAD_DECL_ONLY
void load_18210_20130410(FakeKvApp& fa, bool subscribe=true)
{
    fa.insertDataFromFile(std::string(TEST_SOURCE_DIR)+"/data_18210_20130410.txt");

    fa.insertModelFromFile(std::string(TEST_SOURCE_DIR)+"/model_18210_20130410.txt");

    fa.addStation("18210;10.804;59.923;100.0;OSLO - HOVIN;9;2011-11-22 00:00:00");

    fa.addObsPgm("18210;213;0;1;514;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2011-08-08 00:00:00;null");
    fa.addObsPgm("18210;215;0;1;514;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2011-08-08 00:00:00;null");
    fa.addObsPgm("18210;211;0;1;502;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2011-11-22 00:00:00;null");
    fa.addObsPgm("18210;211;25;1;502;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2011-11-22 00:00:00;null");
    fa.addObsPgm("18210;262;0;1;502;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2011-11-22 00:00:00;null");
    fa.addObsPgm("18210;105;0;1;4;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1999-01-15 00:00:00;null");
    fa.addObsPgm("18210;105;0;1;504;1;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;1;1;1;1;1;1;1;2011-06-29 00:00:00;null");
}
#endif // !LOAD_DECL_ONLY

// generated by '/home/alexanderb/tools/kvhqc/fetch_test_data.py' '-d' '/tmp/ex' '18210' '2013-04-01T00:00' '2013-04-10T10:00' on 2013-04-10T14:13:49.151994
// Local Variables:
// buffer-read-only: t
// End:
