#include "FakeKvApp.hh"
#include "TestHelpers.hh"
#include "KvalobsAccess.hh"
inline TimeSpan t_18700_20141001()
    { return TimeSpan(s2t("2014-10-01 06:00:00"), s2t("2014-10-01 06:00:00")); }
#ifdef LOAD_DECL_ONLY
void load_18700_20141001(FakeKvApp& fa);
#else // LOAD_DECL_ONLY
void load_18700_20141001(FakeKvApp& fa)
{
    fa.insertStation = 18700;
    fa.insertParam = 61;
    fa.insertType = 330;
    fa.insertData("2014-10-01 06:00:00",      51.0,      51.0, "0111000000000010", "");
    fa.insertParam = 81;
    fa.insertData("2014-10-01 06:00:00",       1.2,       1.2, "0111100000100010", "");

    fa.insertStation = 18700;
    fa.insertParam = 61;
    fa.insertModel("2014-10-01 06:00:00",      21.9);
    fa.insertParam = 81;
    fa.insertModel("2014-10-01 06:00:00",       2.7);

    fa.addStation("18700;10.72;59.9423;94.0;OSLO - BLINDERN;13;1941-01-01 00:00:00");

    fa.addObsPgm("18700;61;0;1;308;0;0;0;0;0;0;0;1;0;0;0;0;0;1;0;0;0;0;0;1;0;0;0;0;0;1;1;1;1;1;1;1;1951-01-01 06:00:00;1996-03-18 15:00:00");
    fa.addObsPgm("18700;61;0;1;3;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1992-01-01 00:00:00;2006-04-03 00:00:00");
    fa.addObsPgm("18700;61;0;1;308;0;0;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;1;1;1;1;1;1;1996-03-18 15:00:00;1996-06-01 00:00:00");
    fa.addObsPgm("18700;61;0;1;308;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;1;1;1;1;1;1;1996-06-01 00:00:00;2004-12-31 00:00:00");
    fa.addObsPgm("18700;61;0;1;330;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2006-04-03 00:00:00;null");
    fa.addObsPgm("18700;81;0;1;308;0;0;0;0;0;0;0;1;0;0;0;0;0;1;0;0;0;0;0;1;0;0;0;0;0;1;1;1;1;1;1;1;1951-01-01 06:00:00;1996-03-18 15:00:00");
    fa.addObsPgm("18700;81;0;1;3;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1992-01-01 00:00:00;2006-04-03 00:00:00");
    fa.addObsPgm("18700;81;0;1;308;0;0;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;1;1;1;1;1;1;1996-03-18 15:00:00;1996-06-01 00:00:00");
    fa.addObsPgm("18700;81;0;1;308;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;0;0;1;1;1;1;1;1;1;1996-06-01 00:00:00;2004-12-31 00:00:00");
    fa.addObsPgm("18700;81;0;1;330;0;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;2006-04-03 00:00:00;null");

    fa.addTypes(kvalobs::kvTypes(330,"SMS meldingsformat 30",10,20,"A","h","Automatstasjoner"));
    fa.addTypes(kvalobs::kvTypes(308,"SMS meldingsformat 8",20,5,"M","h","Visuelle observasjoner m param EM"));
    fa.addTypes(kvalobs::kvTypes(3,"autoobs",20,10,"A","h",""));

    fa.addParam(kvalobs::kvParam(61,"DD","Vindretning 10 minutt","vektoriell i grader",0,"Tilhører FF. SYNOP-kodeverdi 99 blir lagret i Kvalobs som -3"));
    fa.addParam(kvalobs::kvParam(81,"FF","Vindhastighet 10 minutt","m/s",0,"10 minutt nåverdi"));

}
#endif // !LOAD_DECL_ONLY

// generated by '/home/alexanderb/tools/kvhqc/fetch_test_data.py' '--params' '61,81' '18700' '2014-10-01 06:00:00' '2014-10-01 06:00:00' on 2014-10-06T10:46:04.960033
// Local Variables:
// buffer-read-only: t
// End:
