# -*- coding: utf-8 -*- 

def update(sdb):
    cur = sdb.cur
    cur.execute("DROP TABLE IF EXISTS check_explain")

    cur.execute("""CREATE TABLE check_explain (
           qcx VARCHAR(16) UNIQUE,
           language CHAR(2) DEFAULT 'nb',
           description VARCHAR(1024)
    )""")

    check_explanations = [
        ('QC1-0-104', u'Forhånds-forkasting av RA'),
        ('QC1-0-105', u'Forhånds-forkasting av RR_01'),
        ('QC1-0-106', u'Forhånds-forkasting av RR_1'),
        ('QC1-0-107', u'Forhånds-forkasting av RR_3'),
        ('QC1-0-108', u'Forhånds-forkasting av RR_6'),
        ('QC1-0-109', u'Forhånds-forkasting av RR_12'),
        ('QC1-0-110', u'Forhånds-forkasting av RR_24'),
        ('QC1-0-112', u'Forhånds-forkasting av SA'),
        ('QC1-0-112_1', u'Forhånds-forkasting av SA'),
        ('QC1-0-121', u'Forhånds-forkasting av OT_1'),
        ('QC1-0-123', u'Forhånds-forkasting av RT_1'),
        ('QC1-0-173', u'Forhånds-forkasting av PO'),
        ('QC1-0-177', u'Forhånds-forkasting av PP'),
        ('QC1-0-178', u'Forhånds-forkasting av PR'),
        ('QC1-0-211', u'Forhånds-forkasting av TA'),
        ('QC1-0-211_1', u'Forhånds-forkasting av TA'),
        ('QC1-0-211_501', u'Forhånds-forkasting av TA'),
        ('QC1-0-211_506', u'Forhånds-forkasting av TA'),
        ('QC1-0-213', u'Forhånds-forkasting av TAN'),
        ('QC1-0-213_1', u'Forhånds-forkasting av TAN'),
        ('QC1-0-215', u'Forhånds-forkasting av TAX'),
        ('QC1-0-215_1', u'Forhånds-forkasting av TAX'),
        ('QC1-0-217', u'Forhånds-forkasting av TD'),
        ('QC1-0-221', u'Forhånds-forkasting av TG'),
        ('QC1-0-223', u'Forhånds-forkasting av TGN'),
        ('QC1-0-227_l10', u'Forhånds-forkasting av TJ'),
        ('QC1-0-227_l20', u'Forhånds-forkasting av TJ'),
        ('QC1-0-242', u'Forhånds-forkasting av TW'),
        ('QC1-0-261', u'Forhånds-forkasting av UH'),
        ('QC1-0-262', u'Forhånds-forkasting av UU'),
        ('QC1-0-328', u'Forhånds-forkasting av RT_010'),
        ('QC1-0-61', u'Forhånds-forkasting av DD'),
        ('QC1-0-73', u'Forhånds-forkasting av DX_1'),
        ('QC1-0-81', u'Forhånds-forkasting av FF'),
        ('QC1-0-84', u'Forhånds-forkasting av FG_010'),
        ('QC1-0-87', u'Forhånds-forkasting av FX_1'),
        ('QC1-0-90', u'Forhånds-forkasting av FG_1'),
        ('QC1-0-autosnow', u'Forhånds-justering av SA (automatisk snødybdemåling) til barmark'),
        ('QC1-0-geonor', u'Forhånds-forkasting. Geonor bøtteverdi er ugyldige i sterk kulde'),

        ('QC1-1-1', u'Grenseverdi-sjekk av AA'),
        ('QC1-1-10', u'Grenseverdi-sjekk av IX'),
        ('QC1-1-101', u'Grenseverdi-sjekk av ES'),
        ('QC1-1-102', u'Grenseverdi-sjekk av EV_1'),
        ('QC1-1-1027', u'Grenseverdi-sjekk av KLFG_1'),
        ('QC1-1-1028', u'Grenseverdi-sjekk av KLFX_1'),
        ('QC1-1-103', u'Grenseverdi-sjekk av EV_24'),
        ('QC1-1-104', u'Grenseverdi-sjekk av RA'),
        ('QC1-1-104x', u'Grenseverdi-sjekk av RA'),
        ('QC1-1-105', u'Grenseverdi-sjekk av RR_01'),
        ('QC1-1-106', u'Grenseverdi-sjekk av RR_1'),
        ('QC1-1-106x', u'Grenseverdi-sjekk av RR_1'),
        ('QC1-1-107', u'Grenseverdi-sjekk av RR_3'),
        ('QC1-1-107x', u'Grenseverdi-sjekk av RR_3'),
        ('QC1-1-108', u'Grenseverdi-sjekk av RR_6'),
        ('QC1-1-108x', u'Grenseverdi-sjekk av RR_6'),
        ('QC1-1-109', u'Grenseverdi-sjekk av RR_12'),
        ('QC1-1-109x', u'Grenseverdi-sjekk av RR_12'),
        ('QC1-1-11', u'Grenseverdi-sjekk av XIS'),
        ('QC1-1-110', u'Grenseverdi-sjekk av RR_24'),
        ('QC1-1-110a', u'Grenseverdi-sjekk av RR_24'),
        ('QC1-1-110b', u'Grenseverdi-sjekk av RR_24'),
        ('QC1-1-110x', u'Grenseverdi-sjekk av RR_24'),
        ('QC1-1-111', u'Grenseverdi-sjekk av RX'),
        ('QC1-1-112', u'Grenseverdi-sjekk av SA'),
        ('QC1-1-112x', u'Grenseverdi-sjekk av SA'),
        ('QC1-1-113', u'Grenseverdi-sjekk av SS_1'),
        ('QC1-1-114', u'Grenseverdi-sjekk av SS_24'),
        ('QC1-1-117', u'Grenseverdi-sjekk av RR_X'),
        ('QC1-1-118', u'Grenseverdi-sjekk av RR_010'),
        ('QC1-1-119', u'Grenseverdi-sjekk av RR_2'),
        ('QC1-1-12', u'Grenseverdi-sjekk av ITR'),
        ('QC1-1-120', u'Grenseverdi-sjekk av RR_9'),
        ('QC1-1-121', u'Grenseverdi-sjekk av OT_1'),
        ('QC1-1-122', u'Grenseverdi-sjekk av OT_24'),
        ('QC1-1-123', u'Grenseverdi-sjekk av RT_1'),
        ('QC1-1-123x', u'Grenseverdi-sjekk av RT_1'),
        ('QC1-1-124', u'Grenseverdi-sjekk av RT_24'),
        ('QC1-1-125', u'Grenseverdi-sjekk av RR_15'),
        ('QC1-1-126', u'Grenseverdi-sjekk av RR_18'),
        ('QC1-1-128', u'Grenseverdi-sjekk av RT_01'),
        ('QC1-1-129a', u'Kodeverdi for EE utenfor tillatt område'),
        ('QC1-1-129b', u'Kodeverdi for EE utenfor tillatt område'),
        ('QC1-1-129', u'Grenseverdi-sjekk av EE'),
        ('QC1-1-13', u'Grenseverdi-sjekk av ITZ'),
        ('QC1-1-130', u'Grenseverdi-sjekk av RTS_1'),
        ('QC1-1-131', u'Grenseverdi-sjekk av HW'),
        ('QC1-1-132', u'Grenseverdi-sjekk av HW1'),
        ('QC1-1-133', u'Grenseverdi-sjekk av HW2'),
        ('QC1-1-134', u'Grenseverdi-sjekk av HWA'),
        ('QC1-1-135', u'Grenseverdi-sjekk av WHMAX'),
        ('QC1-1-136', u'Grenseverdi-sjekk av WHM0'),
        ('QC1-1-137', u'Grenseverdi-sjekk av WH13'),
        ('QC1-1-138', u'Grenseverdi-sjekk av WL'),
        ('QC1-1-14', u'Grenseverdi-sjekk av NH'),
        ('QC1-1-15', u'Grenseverdi-sjekk av NN'),
        ('QC1-1-151', u'Grenseverdi-sjekk av PW'),
        ('QC1-1-152', u'Grenseverdi-sjekk av PW1'),
        ('QC1-1-153', u'Grenseverdi-sjekk av PW2'),
        ('QC1-1-154', u'Grenseverdi-sjekk av PWA'),
        ('QC1-1-155', u'Grenseverdi-sjekk av WTHMAX'),
        ('QC1-1-156', u'Grenseverdi-sjekk av WTMAX'),
        ('QC1-1-157', u'Grenseverdi-sjekk av WTP'),
        ('QC1-1-158', u'Grenseverdi-sjekk av WTP2'),
        ('QC1-1-159', u'Grenseverdi-sjekk av WTS'),
        ('QC1-1-15x', u'Grenseverdi-sjekk av NN'),
        ('QC1-1-16', u'Grenseverdi-sjekk av NNM_24'),
        ('QC1-1-160', u'Grenseverdi-sjekk av WTZ'),
        ('QC1-1-17', u'Grenseverdi-sjekk av RS'),
        ('QC1-1-171', u'Grenseverdi-sjekk av PB'),
        ('QC1-1-172', u'Grenseverdi-sjekk av PH'),
        ('QC1-1-172x', u'Grenseverdi-sjekk av PH'),
        ('QC1-1-173', u'Grenseverdi-sjekk av PO'),
        ('QC1-1-173x', u'Grenseverdi-sjekk av PO'),
        ('QC1-1-174', u'Grenseverdi-sjekk av POM'),
        ('QC1-1-175', u'Grenseverdi-sjekk av PON'),
        ('QC1-1-175x', u'Grenseverdi-sjekk av PON'),
        ('QC1-1-176', u'Grenseverdi-sjekk av POX'),
        ('QC1-1-176x', u'Grenseverdi-sjekk av POX'),
        ('QC1-1-177', u'Grenseverdi-sjekk av PP'),
        ('QC1-1-177x', u'Grenseverdi-sjekk av PP'),
        ('QC1-1-178', u'Grenseverdi-sjekk av PR'),
        ('QC1-1-178x', u'Grenseverdi-sjekk av PR'),
        ('QC1-1-18', u'Grenseverdi-sjekk av SD'),
        ('QC1-1-19', u'Grenseverdi-sjekk av SG'),
        ('QC1-1-191', u'Grenseverdi-sjekk av QA'),
        ('QC1-1-197', u'Grenseverdi-sjekk av QE'),
        ('QC1-1-198', u'Grenseverdi-sjekk av QL'),
        ('QC1-1-199', u'Grenseverdi-sjekk av QLX'),
        ('QC1-1-1x', u'Grenseverdi-sjekk av AA'),
        ('QC1-1-2', u'Grenseverdi-sjekk av BI'),
        ('QC1-1-20', u'Grenseverdi-sjekk av SI'),
        ('QC1-1-200', u'Grenseverdi-sjekk av QO'),
        ('QC1-1-201', u'Grenseverdi-sjekk av QOX'),
        ('QC1-1-202', u'Grenseverdi-sjekk av QR'),
        ('QC1-1-205', u'Grenseverdi-sjekk av QOA'),
        ('QC1-1-207', u'Grenseverdi-sjekk av QK'),
        ('QC1-1-208', u'Grenseverdi-sjekk av QS'),
        ('QC1-1-209', u'Grenseverdi-sjekk av QRA'),
        ('QC1-1-21', u'Grenseverdi-sjekk av ZI'),
        ('QC1-1-210', u'Grenseverdi-sjekk av QLI'),
        ('QC1-1-211', u'Grenseverdi-sjekk av TA'),
        ('QC1-1-211x', u'Grenseverdi-sjekk av TA'),
        ('QC1-1-212', u'Grenseverdi-sjekk av TAM'),
        ('QC1-1-213', u'Grenseverdi-sjekk av TAN'),
        ('QC1-1-213x', u'Grenseverdi-sjekk av TAN'),
        ('QC1-1-214', u'Grenseverdi-sjekk av TAN_12'),
        ('QC1-1-214x', u'Grenseverdi-sjekk av TAN_12'),
        ('QC1-1-215', u'Grenseverdi-sjekk av TAX'),
        ('QC1-1-215x', u'Grenseverdi-sjekk av TAX'),
        ('QC1-1-216', u'Grenseverdi-sjekk av TAX_12'),
        ('QC1-1-216x', u'Grenseverdi-sjekk av TAX_12'),
        ('QC1-1-217', u'Grenseverdi-sjekk av TD'),
        ('QC1-1-217x', u'Grenseverdi-sjekk av TD'),
        ('QC1-1-22', u'Grenseverdi-sjekk av CH'),
        ('QC1-1-221', u'Grenseverdi-sjekk av TG'),
        ('QC1-1-222', u'Grenseverdi-sjekk av TGM'),
        ('QC1-1-223', u'Grenseverdi-sjekk av TGN'),
        ('QC1-1-224', u'Grenseverdi-sjekk av TGN_12'),
        ('QC1-1-225', u'Grenseverdi-sjekk av TGX'),
        ('QC1-1-226', u'Grenseverdi-sjekk av TJ'),
        ('QC1-1-227', u'Grenseverdi-sjekk av TJM'),
        ('QC1-1-228', u'Grenseverdi-sjekk av TNT'),
        ('QC1-1-229', u'Grenseverdi-sjekk av TP'),
        ('QC1-1-23', u'Grenseverdi-sjekk av CL'),
        ('QC1-1-238', u'Grenseverdi-sjekk av TV'),
        ('QC1-1-24', u'Grenseverdi-sjekk av CM'),
        ('QC1-1-242', u'Grenseverdi-sjekk av TW'),
        ('QC1-1-243', u'Grenseverdi-sjekk av TWM'),
        ('QC1-1-244', u'Grenseverdi-sjekk av TWN'),
        ('QC1-1-245', u'Grenseverdi-sjekk av TWX'),
        ('QC1-1-246', u'Grenseverdi-sjekk av TXT'),
        ('QC1-1-248', u'Grenseverdi-sjekk av TAN_X'),
        ('QC1-1-249', u'Grenseverdi-sjekk av TAX_X'),
        ('QC1-1-25', u'Grenseverdi-sjekk av NS1'),
        ('QC1-1-250', u'Grenseverdi-sjekk av TWF'),
        ('QC1-1-251', u'Grenseverdi-sjekk av TAN_24'),
        ('QC1-1-252', u'Grenseverdi-sjekk av TAX_24'),
        ('QC1-1-253', u'Grenseverdi-sjekk av TAM_24'),
        ('QC1-1-26', u'Grenseverdi-sjekk av NS2'),
        ('QC1-1-261', u'Grenseverdi-sjekk av UH'),
        ('QC1-1-262h', u'Grenseverdi-sjekk av UU'),
        ('QC1-1-262x', u'Grenseverdi-sjekk av UU'),
        ('QC1-1-263h', u'Grenseverdi-sjekk av UM'),
        ('QC1-1-264h', u'Grenseverdi-sjekk av UN'),
        ('QC1-1-265h', u'Grenseverdi-sjekk av UX'),
        ('QC1-1-27', u'Grenseverdi-sjekk av NS3'),
        ('QC1-1-271', u'Grenseverdi-sjekk av VMOR'),
        ('QC1-1-271x', u'Grenseverdi-sjekk av VMOR'),
        ('QC1-1-272', u'Grenseverdi-sjekk av VR'),
        ('QC1-1-273', u'Grenseverdi-sjekk av VV'),
        ('QC1-1-274', u'Grenseverdi-sjekk av VZ'),
        ('QC1-1-275', u'Grenseverdi-sjekk av VX'),
        ('QC1-1-28', u'Grenseverdi-sjekk av NS4'),
        ('QC1-1-282', u'Grenseverdi-sjekk av OCT_1'),
        ('QC1-1-283', u'Grenseverdi-sjekk av OCT_24'),
        ('QC1-1-3', u'Grenseverdi-sjekk av BT'),
        ('QC1-1-301', u'Grenseverdi-sjekk av HS1'),
        ('QC1-1-302', u'Grenseverdi-sjekk av HS2'),
        ('QC1-1-303', u'Grenseverdi-sjekk av HS3'),
        ('QC1-1-304', u'Grenseverdi-sjekk av HS4'),
        ('QC1-1-305', u'Grenseverdi-sjekk av CC1'),
        ('QC1-1-306', u'Grenseverdi-sjekk av CC2'),
        ('QC1-1-307', u'Grenseverdi-sjekk av CC3'),
        ('QC1-1-308', u'Grenseverdi-sjekk av CC4'),
        ('QC1-1-309', u'Grenseverdi-sjekk av DVR_02N'),
        ('QC1-1-31', u'Grenseverdi-sjekk av V1'),
        ('QC1-1-310', u'Grenseverdi-sjekk av DVR_02X'),
        ('QC1-1-32', u'Grenseverdi-sjekk av V2'),
        ('QC1-1-328', u'Grenseverdi-sjekk av RT_010'),
        ('QC1-1-33', u'Grenseverdi-sjekk av V3'),
        ('QC1-1-330', u'Grenseverdi-sjekk av RTY_1'),
        ('QC1-1-331', u'Grenseverdi-sjekk av RTR_1'),
        ('QC1-1-332', u'Grenseverdi-sjekk av RTH_1'),
        ('QC1-1-334', u'Grenseverdi-sjekk av ERW'),
        ('QC1-1-335', u'Grenseverdi-sjekk av ERI'),
        ('QC1-1-336', u'Grenseverdi-sjekk av ERF'),
        ('QC1-1-34', u'Grenseverdi-sjekk av V4'),
        ('QC1-1-35', u'Grenseverdi-sjekk av V4S'),
        ('QC1-1-351', u'Grenseverdi-sjekk av BR'),
        ('QC1-1-36', u'Grenseverdi-sjekk av V5'),
        ('QC1-1-361', u'Grenseverdi-sjekk av BBCH11'),
        ('QC1-1-37', u'Grenseverdi-sjekk av V5S'),
        ('QC1-1-38', u'Grenseverdi-sjekk av V6'),
        ('QC1-1-39', u'Grenseverdi-sjekk av V6S'),
        ('QC1-1-4', u'Grenseverdi-sjekk av CI'),
        ('QC1-1-40', u'Grenseverdi-sjekk av V7'),
        ('QC1-1-401', u'Grenseverdi-sjekk av MLAT'),
        ('QC1-1-402', u'Grenseverdi-sjekk av MLON'),
        ('QC1-1-403', u'Grenseverdi-sjekk av MDIR'),
        ('QC1-1-404', u'Grenseverdi-sjekk av MSPEED'),
        ('QC1-1-41', u'Grenseverdi-sjekk av WW'),
        ('QC1-1-42', u'Grenseverdi-sjekk av W1'),
        ('QC1-1-43', u'Grenseverdi-sjekk av W2'),
        ('QC1-1-44', u'Grenseverdi-sjekk av X1WD'),
        ('QC1-1-45', u'Grenseverdi-sjekk av X2WD'),
        ('QC1-1-46', u'Grenseverdi-sjekk av X3WD'),
        ('QC1-1-47', u'Grenseverdi-sjekk av WA1'),
        ('QC1-1-48', u'Grenseverdi-sjekk av WA2'),
        ('QC1-1-49', u'Grenseverdi-sjekk av WAWA'),
        ('QC1-1-49x', u'Grenseverdi-sjekk av WAWA'),
        ('QC1-1-54', u'Grenseverdi-sjekk av HH'),
        ('QC1-1-55', u'Grenseverdi-sjekk av HL'),
        ('QC1-1-56a', u'Grenseverdi-sjekk av HLN'),
        ('QC1-1-56b', u'Grenseverdi-sjekk av HLN'),
        ('QC1-1-56x', u'Grenseverdi-sjekk av HLN'),
        ('QC1-1-57', u'Grenseverdi-sjekk av HM'),
        ('QC1-1-6', u'Grenseverdi-sjekk av DI'),
        ('QC1-1-61', u'Grenseverdi-sjekk av DD'),
        ('QC1-1-61x', u'Grenseverdi-sjekk av DD'),
        ('QC1-1-62', u'Grenseverdi-sjekk av DD_02'),
        ('QC1-1-63', u'Grenseverdi-sjekk av DG'),
        ('QC1-1-64', u'Grenseverdi-sjekk av DDM'),
        ('QC1-1-65', u'Grenseverdi-sjekk av DW1'),
        ('QC1-1-66', u'Grenseverdi-sjekk av DW2'),
        ('QC1-1-67', u'Grenseverdi-sjekk av DX'),
        ('QC1-1-68', u'Grenseverdi-sjekk av WDMT'),
        ('QC1-1-69', u'Grenseverdi-sjekk av DVR_010N'),
        ('QC1-1-7', u'Grenseverdi-sjekk av EM'),
        ('QC1-1-70', u'Grenseverdi-sjekk av DVR_010X'),
        ('QC1-1-71', u'Grenseverdi-sjekk av DVV'),
        ('QC1-1-72', u'Grenseverdi-sjekk av DVX'),
        ('QC1-1-73', u'Grenseverdi-sjekk av DX_1'),
        ('QC1-1-73x', u'Grenseverdi-sjekk av DX_1'),
        ('QC1-1-74', u'Grenseverdi-sjekk av DX_3'),
        ('QC1-1-75', u'Grenseverdi-sjekk av DX_6'),
        ('QC1-1-76', u'Grenseverdi-sjekk av DX_12'),
        ('QC1-1-77', u'Grenseverdi-sjekk av DG_010'),
        ('QC1-1-78', u'Grenseverdi-sjekk av DG_1'),
        ('QC1-1-79', u'Grenseverdi-sjekk av DG_6'),
        ('QC1-1-80', u'Grenseverdi-sjekk av DG_12'),
        ('QC1-1-81', u'Grenseverdi-sjekk av FF'),
        ('QC1-1-81x', u'Grenseverdi-sjekk av FF'),
        ('QC1-1-82', u'Grenseverdi-sjekk av FF_02'),
        ('QC1-1-83', u'Grenseverdi-sjekk av FG'),
        ('QC1-1-84', u'Grenseverdi-sjekk av FG_010'),
        ('QC1-1-84x', u'Grenseverdi-sjekk av FG_010'),
        ('QC1-1-85', u'Grenseverdi-sjekk av FM'),
        ('QC1-1-86', u'Grenseverdi-sjekk av FX'),
        ('QC1-1-87', u'Grenseverdi-sjekk av FX_1'),
        ('QC1-1-87x', u'Grenseverdi-sjekk av FX_1'),
        ('QC1-1-88', u'Grenseverdi-sjekk av FX_6'),
        ('QC1-1-89', u'Grenseverdi-sjekk av FX_12'),
        ('QC1-1-9', u'Grenseverdi-sjekk av IR'),
        ('QC1-1-90', u'Grenseverdi-sjekk av FG_1'),
        ('QC1-1-90x', u'Grenseverdi-sjekk av FG_1'),
        ('QC1-1-91', u'Grenseverdi-sjekk av FG_6'),
        ('QC1-1-92', u'Grenseverdi-sjekk av FG_12'),
        ('QC1-1-93', u'Grenseverdi-sjekk av FX_X'),
        ('QC1-1-94', u'Grenseverdi-sjekk av FG_X'),
        ('QC1-1-95', u'Grenseverdi-sjekk av FX_3'),
        ('QC1-1-96', u'Grenseverdi-sjekk av DAq'),

        ('QC1-2-100', u'Ikke samsvar mellom værsymboler og synsvidde/værkode'),
        ('QC1-2-101', u'Ikke samsvar mellom synsvidde og værkode'),
        ('QC1-2-105', u'Ikke samsvar mellom synsvidde og værkode'),
        ('QC1-2-106', u'Ikke samsvar mellom skydekke og værkode'),
        ('QC1-2-107', u'Ikke samsvar mellom værkode og temperatur (TA>4°C)'),
        ('QC1-2-108', u'Ikke samsvar mellom værkode og temperatur (TA>7°C)'),
        ('QC1-2-109', u'Ikke samsvar mellom værkode og temperatur (TA>-2°C)'),
        ('QC1-2-121.b', u'NN mindre enn NH'),
        ('QC1-2-122.aa', u'NN mindre enn NS (NS1)'),
        ('QC1-2-122.ab', u'NN mindre enn NS (NS2)'),
        ('QC1-2-122.ac', u'NN mindre enn NS (NS3)'),
        ('QC1-2-122.ad', u'NN mindre enn NS (NS4)'),
        ('QC1-2-123.a', u'Ikke samsvar mellom mengde av lave skyer og skyer'),
        ('QC1-2-123.b', u'Ikke samsvar mellom mengde av lave skyer og høyde opp til de laveste skyene'),
        ('QC1-2-123.c', u'Ikke samsvar mellom skyer og skyhøyde'),
        ('QC1-2-124.a', u'Ikke samsvar mellom mengde av lave skyer og skyer'),
        ('QC1-2-125.a', u'Ikke samsvar mellom mengde av lave skyer og skyer'),
        ('QC1-2-126.b', u'Ikke samsvar mellom skymengde og skyer'),
        ('QC1-2-126.c', u'NN=0 og forskjellig fra NH'),
        ('QC1-2-127', u'Ikke samsvar mellom total skymengde og skyer'),
        ('QC1-2-128.11', u'Ikke samsvar mellom total skymengde og mengde av lave skyer'),
        ('QC1-2-128.1', u'Ikke samsvar mellom total skymengde og mengde av lave skyer'),
        ('QC1-2-128.308', u'Ikke samsvar mellom total skymengde og mengde av lave skyer'),
        ('QC1-2-128.312', u'Ikke samsvar mellom total skymengde og mengde av lave skyer'),
        ('QC1-2-128.316', u'Ikke samsvar mellom total skymengde og mengde av lave skyer'),
        ('QC1-2-128.322', u'Ikke samsvar mellom total skymengde og mengde av lave skyer'),
        ('QC1-2-129.b', u'Ikke samsvar mellom mengde av lave skyer og skykoder'),
        ('QC1-2-130.a_131', u'Ikke samsvar mellom mengde av lave skyer og kode høye skyer'),
        ('QC1-2-132', u'Ikke samsvar mellom mengde av lave skyer og skyer'),
        ('QC1-2-133', u'Ikke samsvar mellom mengde av lave skyer og kode lave skyer'),
        ('QC1-2-134.b', u'Ikke samsvar mellom total skymengde og skykoder'),
        ('QC1-2-135', u'Ikke samsvar mellom skymengde og skyhøyde'),
        ('QC1-2-136', u'Ikke samsvar mellom skymengde og skyhøyde'),
        ('QC1-2-137', u'Ikke samsvar mellom total skymengde og mengde av lave skyer'),
        ('QC1-2-138A', u'Ikke samsvar mellom total skymengde og mengde av C-skyer (NS1)'),
        ('QC1-2-138B', u'Ikke samsvar mellom total skymengde og mengde av C-skyer (NS2)'),
        ('QC1-2-138C', u'Ikke samsvar mellom total skymengde og mengde av C-skyer (NS3)'),
        ('QC1-2-138D', u'Ikke samsvar mellom total skymengde og mengde av C-skyer (NS4)'),
        ('QC1-2-139.a', u'Ikke samsvar mellom skykoder og skymengde'),
        ('QC1-2-139.b', u'Ikke samsvar mellom skykoder og skymengde'),
        ('QC1-2-142', u'Ikke samsvar mellom skyangivelser'),
        ('QC1-2-143', u'Ikke samsvar mellom skyangivelser'),
        ('QC1-2-144', u'Ikke samsvar mellom skyangivelser'),
        ('QC1-2-145', u'Ikke samsvar mellom skyangivelser'),
        ('QC1-2-146.a', u'Ikke samsvar mellom lave skyer og hovedtype av skyer'),
        ('QC1-2-146.b', u'Ikke samsvar mellom lave skyer og hovedtype av skyer'),
        ('QC1-2-146.c', u'Ikke samsvar mellom lave skyer og hovedtype av skyer'),
        ('QC1-2-146.d', u'Ikke samsvar mellom lave skyer og hovedtype av skyer'),
        ('QC1-2-147_148.a', u'Ikke samsvar mellom lave skyer og hovedtype av skyer (CC1)'),
        ('QC1-2-147_148.b', u'Ikke samsvar mellom lave skyer og hovedtype av skyer (CC2)'),
        ('QC1-2-147_148.c', u'Ikke samsvar mellom lave skyer og hovedtype av skyer (CC3)'),
        ('QC1-2-147_148.d', u'Ikke samsvar mellom lave skyer og hovedtype av skyer (CC4)'),
        ('QC1-2-149.a', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC1)'),
        ('QC1-2-149.b', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC2)'),
        ('QC1-2-149.c', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC3)'),
        ('QC1-2-149.d', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC4)'),
        ('QC1-2-150.a', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC1)'),
        ('QC1-2-150.b', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC2)'),
        ('QC1-2-150.c', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC3)'),
        ('QC1-2-150.d', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC4)'),
        ('QC1-2-151.a', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC1)'),
        ('QC1-2-151.b', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC2)'),
        ('QC1-2-151.c', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC3)'),
        ('QC1-2-151.d', u'Ikke samsvar mellom mellomhøye skyer og hovedtype av skyer (CC4)'),
        ('QC1-2-152', u'Ikke samsvar mellom skyangivelser'),
        ('QC1-2-153', u'Ikke samsvar mellom skyangivelser'),
        ('QC1-2-154', u'Ikke samsvar mellom skyangivelser'),
        ('QC1-2-155', u'Ikke samsvar mellom total skymengde og skykode høye skyer'),
        ('QC1-2-156.a', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-156.b', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-156.c', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-156.d', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-157.a', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-157.b', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-157.c', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-157.d', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-158.a', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-158.b', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-158.c', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-158.d', u'Ikke samsvar mellom hovedtype av skyer og skymengde'),
        ('QC1-2-159.a', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-159.b', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-159.c', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-159.d', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-160.a', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-160.b', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-160.c', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-160.d', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-161.a', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-161.b', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-161.c', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-161.d', u'Ikke samsvar mellom hovedtype av skyer og skytype'),
        ('QC1-2-162.a', u'Ikke samsvar mellom hovedtype av skyer og øvrig skyinformasjon'),
        ('QC1-2-162.b', u'Ikke samsvar mellom hovedtype av skyer og øvrig skyinformasjon'),
        ('QC1-2-162.c', u'Ikke samsvar mellom hovedtype av skyer og øvrig skyinformasjon'),
        ('QC1-2-162.d', u'Ikke samsvar mellom hovedtype av skyer og øvrig skyinformasjon'),
        ('QC1-2-163.a', u'Ikke samsvar mellom hovedtype av skyer og øvrig skyinformasjon'),
        ('QC1-2-163.b', u'Ikke samsvar mellom hovedtype av skyer og øvrig skyinformasjon'),
        ('QC1-2-163.c', u'Ikke samsvar mellom hovedtype av skyer og øvrig skyinformasjon'),
        ('QC1-2-163.d', u'Ikke samsvar mellom hovedtype av skyer og øvrig skyinformasjon'),
        ('QC1-2-164', u'Inkonsistens i skygruppe 8NsChshs'),
        ('QC1-2-165', u'Inkonsistens i skygruppe 8NsChshs'),
        ('QC1-2-166', u'Inkonsistens i skygruppe 8NsChshs'),
        ('QC1-2-167', u'Inkonsistens i skygruppe 8NsChshs'),
        ('QC1-2-168', u'Inkonsistens i skygruppe 8NsChshs'),
        ('QC1-2-168b', u'Inkonsistens i skygruppe 8NsChshs'),
        ('QC1-2-169', u'Ikke samsvar mellom skytype og skyhøyde'),
        ('QC1-2-170', u'Ikke samsvar mellom skytype og skyhøyde'),
        ('QC1-2-171', u'Ikke samsvar mellom skytype og skyhøyde'),
        ('QC1-2-172', u'Ikke samsvar mellom skytype og skyhøyde'),
        ('QC1-2-173', u'Ikke samsvar mellom skyer og skyhøyde'),
        ('QC1-2-175', u'Ikke samsvar mellom skymengde og skyer'),
        ('QC1-2-177', u'TAX antatt feil fortegn'),
        ('QC1-2-177b', u'TAX_12 antatt feil fortegn'),
        ('QC1-2-178', u'Ikke samsvar mellom TAN og TAX'),
        ('QC1-2-21', u'AA mangler, PP eksisterer'),
        ('QC1-2-22', u'AA eksisterer, PP mangler'),
        ('QC1-2-23', u'AA=4 (konstant), PP forskjellig fra 0'),
        ('QC1-2-24', u'PP=0, AA=1-3'),
        ('QC1-2-25', u'PP=0, AA=6-8'),
        ('QC1-2-26', u'Sjekk trykkreduksjon til havets nivå'),
        ('QC1-2-27.a', u'Ikke samsvar mellom trykkendring (PR) og trykktendens'),
        ('QC1-2-27.b', u'Ikke samsvar mellom trykkendring (PO) og trykktendens'),
        ('QC1-2-303', u'Ikke samsvar mellom markas tilstand og snødybde'),
        ('QC1-2-304.a', u'Inkonsistens i markas tilstand og snødybde'),
        ('QC1-2-304.b', u'Inkonsistens i markas tilstand og snødybde'),
        ('QC1-2-305a', u'Flekkvis snø(EE) med snødybde(SA)'),
        ('QC1-2-305b', u'Flekkvis snø(EE) med snødybde(SA)'),
        ('QC1-2-306a', u'Snø dekker marka(EE) uten snødybde(SA)'),
        ('QC1-2-306b', u'Snø dekker marka(EE) uten snødybde(SA)'),
        ('QC1-2-307a', u'Snø dekker ikke marka(EE) med snødybde(SA)'),
        ('QC1-2-307b', u'Snø dekker ikke marka(EE) med snødybde(SA)'),
        ('QC1-2-31B', u'Ikke samsvar mellom TAN_12 og TA'),
        ('QC1-2-32', u'TAN_12 for høy eller TAX_12 for lav, eller de er byttet om'),
        ('QC1-2-328', u'Ikke samsvar mellom skydekke og W1 eller W2'),
        ('QC1-2-33B', u'Ikke samsvar mellom TAX_12 og TA'),
        ('QC1-2-34', u'TA timeobs for høy eller TAX_12 for lav'),
        ('QC1-2-35', u'TA timeobs for lav eller TAN_12 for høy'),
        ('QC1-2-36', u'TD for høy eller TA for lav'),
        ('QC1-2-37', u'TAM større enn TAX'),
        ('QC1-2-38b', u'TAN større enn TA'),
        ('QC1-2-38', u'TA større enn TAX'),
        ('QC1-2-39', u'TAN større enn TAM'),
        ('QC1-2-40', u'TAN større enn TAX'),
        ('QC1-2-41', u'Ikke samsvar mellom DD og FF'),
        ('QC1-2-42', u'Ikke samsvar mellom DD og FF'),
        ('QC1-2-43.a', u'Ikke samsvar mellom DD og FF'),
        ('QC1-2-43.b', u'Ikke samsvar mellom DD og FF'),
        ('QC1-2-44', u'FF større enn FX'),
        ('QC1-2-45a', u'FF for høy eller FX for lav (siste 6 timer)'),
        ('QC1-2-45b', u'FF for høy eller FX for lav (siste 3 timer)'),
        ('QC1-2-46A', u'FX større enn FG'),
        ('QC1-2-46B', u'FX>4.5 m/s & FX=FG'),
        ('QC1-2-46C', u'FX_1>FG_1 og FX_1>FG_010forrige time'),
        ('QC1-2-46D', u'FX_6 større enn FG_6'),
        ('QC1-2-46E', u'FX_12 større enn FG_12'),
        ('QC1-2-47', u'FF forskjellig fra Beaufortskala-verdier'),
        ('QC1-2-48', u'FF større enn FG'),
        ('QC1-2-49', u'FM større enn FX'),
        ('QC1-2-50', u'FM større enn FG'),
        ('QC1-2-61.a', u'Ikke samsvar mellom RR_6 og iR (Synop-koden, iR=1)'),
        ('QC1-2-61.b', u'Ikke samsvar mellom RR_12 og iR (Synop-koden, iR=1)'),
        ('QC1-2-62.a', u'Ikke samsvar mellom RR_6 og iR (Synop-koden, iR=3)'),
        ('QC1-2-62.b', u'Ikke samsvar mellom RR_12 og iR (Synop-koden, iR=3)'),
        ('QC1-2-63.a', u'Ikke samsvar mellom RR_6 og iR (Synop-koden, iR=4)'),
        ('QC1-2-63.b', u'Ikke samsvar mellom RR_12 og iR (Synop-koden, iR=4)'),
        ('QC1-2-64A', u'Observert nedbør (W1), men observert ingen nedbørhøyde'),
        ('QC1-2-64B', u'Observert nedbør (W1), men observert ingen nedbørhøyde'),
        ('QC1-2-65a', u'Ikke samsvar mellom nedbørsymboler og RR_6'),
        ('QC1-2-65b', u'Ikke samsvar mellom nedbørsymboler og RR_12'),
        ('QC1-2-65c', u'Ikke samsvar mellom nedbørsymboler og RR_24'),
        ('QC1-2-67', u'Nedbørmengde (RR_12) mangler iflg. værkode W1 / W2'),
        ('QC1-2-68', u'Nedbørmengde mangler (RR_12) iflg. værkode ww'),
        ('QC1-2-69.a', u'Nedbørmengde (RR_6) mangler iflg. værkode W1 / W2'),
        ('QC1-2-69.b', u'Nedbørmengde mangler (RR_6) iflg. værkode ww'),
        ('QC1-2-70_71', u'RR_6 større enn RR_12'),
        ('QC1-2-72.a', u'Snødekke for lavt i forhold til snødybde'),
        ('QC1-2-72.b10', u'Snødybden synker mer enn 15cm ned til 0cm i "Snødøgn".'),
        ('QC1-2-72.b11', u'Ingen nedbørhøyde - men det er "Nedbørdøgn".'),
        ('QC1-2-72.b12', u'Det er nedbørhøyde - men ikke "Nedbørdøgn".'),
        ('QC1-2-72.b1', u'Ikke bare dugg eller rim (RR_24>0.5).'),
        ('QC1-2-72.b4', u'"Snødøgn" - uten snødybde.'),
        ('QC1-2-72.b5', u'"Snødøgn" - Snødybden øker ikke (RR_24>=10mm).'),
        ('QC1-2-72.b6', u'Snødybden øker uten "Snødøgn".'),
        ('QC1-2-72.b7', u'Snødybden øker mer enn nedbørmengden tilsier.'),
        ('QC1-2-72.b8', u'Snødybden avtar mer enn 15cm når RR_24>1.0 og det er "Snødøgn".'),
        ('QC1-2-72.b9', u'Snødybden avtar for mye i "Regndøgn".'),
        ('QC1-2-72.c10', u'Snødybden synker mer enn 15cm ned til 0cm i "Snødøgn".'),
        ('QC1-2-72.c11', u'Ingen nedbørhøyde - men det er "Nedbørdøgn".'),
        ('QC1-2-72.c12', u'Det er nedbørhøyde - men ikke "Nedbørdøgn".'),
        ('QC1-2-72.c1', u'Ikke bare dugg eller rim (RR_24>0.5).'),
        ('QC1-2-72.c4', u'"Snødøgn" - uten snødybde.'),
        ('QC1-2-72.c5', u'"Snødøgn" - Snødybden øker ikke (RR_24>=10mm).'),
        ('QC1-2-72.c6', u'Snødybden øker uten "Snødøgn".'),
        ('QC1-2-72.c7', u'Snødybden øker mer enn nedbørmengden tilsier.'),
        ('QC1-2-72.c8', u'Snødybden avtar mer enn 15cm når RR_24>1.0 og det er "Snødøgn".'),
        ('QC1-2-72.c9', u'Snødybden avtar for mye i "Regndøgn".'),
        ('QC1-2-73', u'Ikke samsvar mellom RR_1 og nedbørtid i minutter (RT_1)'),
        ('QC1-2-74', u'Ikke samsvar mellom RR_1 og nedbørtid i minutter (RT_1)'),
        ('QC1-2-75', u'Ikke samsvar mellom RR_1 og bladfuktighet i minutter (BT)'),
        ('QC1-2-76', u'Ikke samsvar mellom RR_1 og bladfuktighet i minutter (BT)'),
        ('QC1-2-77', u'Bøtteverdien har økt uten verdi fra ja/nei-sensoren'),
        ('QC1-2-81', u'Ikke samsvar mellom værkode og synsvidde'),
        ('QC1-2-82', u'Ikke samsvar mellom værkode og synsvidde'),
        ('QC1-2-83a', u'Ikke samsvar mellom værkode og synsvidde'),
        ('QC1-2-84', u'Ikke samsvar mellom værkode og synsvidde'),
        ('QC1-2-86', u'Ikke samsvar mellom værkode og synsvidde'),
        ('QC1-2-90', u'W1 mindre enn W2'),
        ('QC1-2-92', u'Ikke samsvar mellom skydekke og værkode (tåke med skimt av himmel)'),
        ('QC1-2-93', u'Ikke samsvar mellom skydekke og værkode (tåke uten skimt av himmel)'),
        ('QC1-2-94', u'Ikke samsvar mellom skydekke og værkode'),
        ('QC1-2-95', u'Ikke samsvar mellom mengde av lave skyer og værkode'),
        ('QC1-2-96', u'Ikke samsvar mellom værkode og skytype'),
        ('QC1-2-97', u'Ikke samsvar mellom værkode og skytype'),
        ('QC1-2-99', u'Ikke samsvar mellom ww og ix (Synop-koden, ix=1-2)'),

        ('QC1-3a-1', u'Sprang-sjekk. Synking eller økning av AA siden forrige obs større enn testverdi'),
        ('QC1-3a-104', u'Sprang-sjekk. Synking eller økning av RA siden forrige obs større enn testverdi'),
        ('QC1-3a-104drift', u'Drift i bøtteverdien over siste døgn'),
        ('QC1-3a-105', u'Sprang-sjekk. Synking eller økning av RR_01 siden forrige obs større enn testverdi'),
        ('QC1-3a-112', u'Sprang-sjekk. Synking eller økning av SA siden forrige obs større enn testverdi'),
        ('QC1-3a-113', u'Sprang-sjekk. Synking eller økning av SS_1 siden forrige obs større enn testverdi'),
        ('QC1-3a-123', u'Sprang-sjekk. Synking eller økning av RT_1 siden forrige obs større enn testverdi'),
        ('QC1-3a-135', u'Sprang-sjekk. Synking eller økning av WHMAX siden forrige obs større enn testverdi'),
        ('QC1-3a-136', u'Sprang-sjekk. Synking eller økning av WHM0 siden forrige obs større enn testverdi'),
        ('QC1-3a-172', u'Sprang-sjekk. Synking eller økning av PH siden forrige obs større enn testverdi'),
        ('QC1-3a-174', u'Sprang-sjekk. Synking eller økning av POM siden forrige obs større enn testverdi'),
        ('QC1-3a-175', u'Sprang-sjekk. Synking eller økning av PON siden forrige obs større enn testverdi'),
        ('QC1-3a-176', u'Sprang-sjekk. Synking eller økning av POX siden forrige obs større enn testverdi'),
        ('QC1-3a-178', u'Sprang-sjekk. Synking eller økning av PR siden forrige obs større enn testverdi'),
        ('QC1-3a-197', u'Sprang-sjekk. Synking eller økning av QE siden forrige obs større enn testverdi'),
        ('QC1-3a-198', u'Sprang-sjekk. Synking eller økning av QL siden forrige obs større enn testverdi'),
        ('QC1-3a-199', u'Sprang-sjekk. Synking eller økning av QLX siden forrige obs større enn testverdi'),
        ('QC1-3a-2', u'Sprang-sjekk. Synking eller økning av BI siden forrige obs større enn testverdi'),
        ('QC1-3a-200', u'Sprang-sjekk. Synking eller økning av QO siden forrige obs større enn testverdi'),
        ('QC1-3a-201', u'Sprang-sjekk. Synking eller økning av QOX siden forrige obs større enn testverdi'),
        ('QC1-3a-211', u'Sprang-sjekk. Synking eller økning av TA siden forrige obs større enn testverdi'),
        ('QC1-3a-212', u'Sprang-sjekk. Synking eller økning av TAM siden forrige obs større enn testverdi'),
        ('QC1-3a-213', u'Sprang-sjekk. Synking eller økning av TAN siden forrige obs større enn testverdi'),
        ('QC1-3a-215', u'Sprang-sjekk. Synking eller økning av TAX siden forrige obs større enn testverdi'),
        ('QC1-3a-221', u'Sprang-sjekk. Synking eller økning av TG siden forrige obs større enn testverdi'),
        ('QC1-3a-222', u'Sprang-sjekk. Synking eller økning av TGM siden forrige obs større enn testverdi'),
        ('QC1-3a-223', u'Sprang-sjekk. Synking eller økning av TGN siden forrige obs større enn testverdi'),
        ('QC1-3a-225', u'Sprang-sjekk. Synking eller økning av TGX siden forrige obs større enn testverdi'),
        ('QC1-3a-227', u'Sprang-sjekk. Synking eller økning av TJM siden forrige obs større enn testverdi'),
        ('QC1-3a-238', u'Sprang-sjekk. Synking eller økning av TV siden forrige obs større enn testverdi'),
        ('QC1-3a-262', u'Sprang-sjekk. Synking eller økning av UU siden forrige obs større enn testverdi'),
        ('QC1-3a-264', u'Sprang-sjekk. Synking eller økning av UN siden forrige obs større enn testverdi'),
        ('QC1-3a-265', u'Sprang-sjekk. Synking eller økning av UX siden forrige obs større enn testverdi'),
        ('QC1-3a-81', u'Sprang-sjekk. Synking eller økning av FF siden forrige obs større enn testverdi'),
        ('QC1-3a-85', u'Sprang-sjekk. Synking eller økning av FM siden forrige obs større enn testverdi'),
        ('QC1-3a-87', u'Sprang-sjekk. Synking eller økning av FX_1 siden forrige obs større enn testverdi'),
        ('QC1-3b-1', u'Frys-sjekk. Varighet av samme verdi av AA større enn testverdi'),
        ('QC1-3b-104', u'Frys-sjekk. Varighet av samme verdi av RA større enn testverdi'),
        ('QC1-3b-135', u'Frys-sjekk. Varighet av samme verdi av WHMAX større enn testverdi'),
        ('QC1-3b-136', u'Frys-sjekk. Varighet av samme verdi av WHM0 større enn testverdi'),
        ('QC1-3b-172', u'Frys-sjekk. Varighet av samme verdi av PH større enn testverdi'),
        ('QC1-3b-174', u'Frys-sjekk. Varighet av samme verdi av POM større enn testverdi'),
        ('QC1-3b-175', u'Frys-sjekk. Varighet av samme verdi av PON større enn testverdi'),
        ('QC1-3b-176', u'Frys-sjekk. Varighet av samme verdi av POX større enn testverdi'),
        ('QC1-3b-177', u'Frys-sjekk. Varighet av samme verdi av PP større enn testverdi'),
        ('QC1-3b-197', u'Frys-sjekk. Varighet av samme verdi av QE større enn testverdi'),
        ('QC1-3b-198', u'Frys-sjekk. Varighet av samme verdi av QL større enn testverdi'),
        ('QC1-3b-199', u'Frys-sjekk. Varighet av samme verdi av QLX større enn testverdi'),
        ('QC1-3b-2', u'Frys-sjekk. Varighet av samme verdi av BI større enn testverdi'),
        ('QC1-3b-200', u'Frys-sjekk. Varighet av samme verdi av QO større enn testverdi'),
        ('QC1-3b-201', u'Frys-sjekk. Varighet av samme verdi av QOX større enn testverdi'),
        ('QC1-3b-211', u'Frys-sjekk. Varighet av samme verdi av TA større enn testverdi'),
        ('QC1-3b-212', u'Frys-sjekk. Varighet av samme verdi av TAM større enn testverdi'),
        ('QC1-3b-213', u'Frys-sjekk. Varighet av samme verdi av TAN større enn testverdi'),
        ('QC1-3b-215', u'Frys-sjekk. Varighet av samme verdi av TAX større enn testverdi'),
        ('QC1-3b-221', u'Frys-sjekk. Varighet av samme verdi av TG større enn testverdi'),
        ('QC1-3b-222', u'Frys-sjekk. Varighet av samme verdi av TGM større enn testverdi'),
        ('QC1-3b-223', u'Frys-sjekk. Varighet av samme verdi av TGN større enn testverdi'),
        ('QC1-3b-225', u'Frys-sjekk. Varighet av samme verdi av TGX større enn testverdi'),
        ('QC1-3b-227', u'Frys-sjekk. Varighet av samme verdi av TJM større enn testverdi'),
        ('QC1-3b-238', u'Frys-sjekk. Varighet av samme verdi av TV større enn testverdi'),
        ('QC1-3b-262', u'Frys-sjekk. Varighet av samme verdi av UU større enn testverdi'),
        ('QC1-3b-264', u'Frys-sjekk. Varighet av samme verdi av UN større enn testverdi'),
        ('QC1-3b-265', u'Frys-sjekk. Varighet av samme verdi av UX større enn testverdi'),
        ('QC1-3b-61', u'Frys-sjekk. Varighet av samme verdi av DD større enn testverdi'),
        ('QC1-3b-63', u'Frys-sjekk. Varighet av samme verdi av DG større enn testverdi'),
        ('QC1-3b-64', u'Frys-sjekk. Varighet av samme verdi av DDM større enn testverdi'),
        ('QC1-3b-67', u'Frys-sjekk. Varighet av samme verdi av DX større enn testverdi'),
        ('QC1-3b-81', u'Frys-sjekk. Varighet av samme verdi av FF større enn testverdi'),
        ('QC1-3b-85', u'Frys-sjekk. Varighet av samme verdi av FM større enn testverdi'),
        ('QC1-3b-86', u'Frys-sjekk. Varighet av samme verdi av FX større enn testverdi'),
        ('QC1-3b-87', u'Frys-sjekk. Varighet av samme verdi av FX_1 større enn testverdi'),
        ('QC1-3b-88', u'Frys-sjekk. Varighet av samme verdi av FX_6 større enn testverdi'),
        ('QC1-3b-89', u'Frys-sjekk. Varighet av samme verdi av FX_12 større enn testverdi'),
        ('QC1-3b-90', u'Frys-sjekk. Varighet av samme verdi av FG_1 større enn testverdi'),
        ('QC1-3b-91', u'Frys-sjekk. Varighet av samme verdi av FG_6 større enn testverdi'),
        ('QC1-3b-92', u'Frys-sjekk. Varighet av samme verdi av FG_12 større enn testverdi'),
        ('QC1-3b-93', u'Frys-sjekk. Varighet av samme verdi av FX_X større enn testverdi'),
        ('QC1-3b-94', u'Frys-sjekk. Varighet av samme verdi av FG_X større enn testverdi'),
        ('QC1-3b-95', u'Frys-sjekk. Varighet av samme verdi av FX_3 større enn testverdi'),
        ('QC1-3c-1', u'Dip- og Peak-sjekk. Dip eller peak av AA større enn testverdi'),
        ('QC1-3c-104', u'Dip- og Peak-sjekk. Dip eller peak av RA større enn testverdi'),
        ('QC1-3c-105', u'Dip- og Peak-sjekk. Dip eller peak av RR_01 større enn testverdi'),
        ('QC1-3c-112', u'Dip- og Peak-sjekk. Dip eller peak av SA større enn testverdi'),
        ('QC1-3c-113', u'Dip- og Peak-sjekk. Dip eller peak av SS_1 større enn testverdi'),
        ('QC1-3c-135', u'Dip- og Peak-sjekk. Dip eller peak av WHMAX større enn testverdi'),
        ('QC1-3c-136', u'Dip- og Peak-sjekk. Dip eller peak av WHM0 større enn testverdi'),
        ('QC1-3c-172', u'Dip- og Peak-sjekk. Dip eller peak av PH større enn testverdi'),
        ('QC1-3c-174', u'Dip- og Peak-sjekk. Dip eller peak av POM større enn testverdi'),
        ('QC1-3c-175', u'Dip- og Peak-sjekk. Dip eller peak av PON større enn testverdi'),
        ('QC1-3c-176', u'Dip- og Peak-sjekk. Dip eller peak av POX større enn testverdi'),
        ('QC1-3c-177', u'Dip- og Peak-sjekk. Dip eller peak av PP større enn testverdi'),
        ('QC1-3c-178', u'Dip- og Peak-sjekk. Dip eller peak av PR større enn testverdi'),
        ('QC1-3c-197', u'Dip- og Peak-sjekk. Dip eller peak av QE større enn testverdi'),
        ('QC1-3c-198', u'Dip- og Peak-sjekk. Dip eller peak av QL større enn testverdi'),
        ('QC1-3c-199', u'Dip- og Peak-sjekk. Dip eller peak av QLX større enn testverdi'),
        ('QC1-3c-2', u'Dip- og Peak-sjekk. Dip eller peak av BI større enn testverdi'),
        ('QC1-3c-200', u'Dip- og Peak-sjekk. Dip eller peak av QO større enn testverdi'),
        ('QC1-3c-201', u'Dip- og Peak-sjekk. Dip eller peak av QOX større enn testverdi'),
        ('QC1-3c-211', u'Dip- og Peak-sjekk. Dip eller peak av TA større enn testverdi'),
        ('QC1-3c-212', u'Dip- og Peak-sjekk. Dip eller peak av TAM større enn testverdi'),
        ('QC1-3c-213', u'Dip- og Peak-sjekk. Dip eller peak av TAN større enn testverdi'),
        ('QC1-3c-215', u'Dip- og Peak-sjekk. Dip eller peak av TAX større enn testverdi'),
        ('QC1-3c-221', u'Dip- og Peak-sjekk. Dip eller peak av TG større enn testverdi'),
        ('QC1-3c-222', u'Dip- og Peak-sjekk. Dip eller peak av TGM større enn testverdi'),
        ('QC1-3c-223', u'Dip- og Peak-sjekk. Dip eller peak av TGN større enn testverdi'),
        ('QC1-3c-225', u'Dip- og Peak-sjekk. Dip eller peak av TGX større enn testverdi'),
        ('QC1-3c-227', u'Dip- og Peak-sjekk. Dip eller peak av TJM større enn testverdi'),
        ('QC1-3c-238', u'Dip- og Peak-sjekk. Dip eller peak av TV større enn testverdi'),
        ('QC1-3c-262', u'Dip- og Peak-sjekk. Dip eller peak av UU større enn testverdi'),
        ('QC1-3c-264', u'Dip- og Peak-sjekk. Dip eller peak av UN større enn testverdi'),
        ('QC1-3c-265', u'Dip- og Peak-sjekk. Dip eller peak av UX større enn testverdi'),
        ('QC1-3c-81', u'Dip- og Peak-sjekk. Dip eller peak av FF større enn testverdi'),
        ('QC1-3c-85', u'Dip- og Peak-sjekk. Dip eller peak av FM større enn testverdi'),
        ('QC1-3c-87', u'Dip- og Peak-sjekk. Dip eller peak av FX_1 større enn testverdi'),

        ('QC1-4-109', u'Observasjon avviker merkbart fra modellverdi for parameter RR_12'),
        ('QC1-4-178', u'Observasjon avviker merkbart fra modellverdi for parameter PR'),
        ('QC1-4-211', u'Observasjon avviker merkbart fra modellverdi for parameter TA'),
        ('QC1-4-213', u"TAN's avvik fra TA's laveste modellverdi fra forrige obs større enn testverdi"),
        ('QC1-4-215', u"TAX's avvik fra TA's hoyeste modellverdi fra forrige obs større enn testverdi"),
        ('QC1-4-262', u'Observasjon avviker merkbart fra modellverdi for parameter UU'),
        ('QC1-4-81', u'Observasjon avviker merkbart fra modellverdi for parameter FF'),

        ('QC1-6-111', u'Forholdet mellom snøfokk og vindhastighet'),
        ('QC1-6-112', u'Forholdet mellom snøfokk og vindhastighet'),
        ('QC1-6-176', u'Ikke samsvar mellom skymengde og sikt'),
        ('QC1-6-211', u'Stort avvik mellom TAN_12 og TA i samme periode (15 grader)'),
        ('QC1-6-212', u'Stort avvik mellom TAN_12 (kl.06) og TA i samme periode (9 grader)'),
        ('QC1-6-213', u'Stort avvik mellom TAN_12 (kl.06) og TA (kl.06) (10 grader)'),
        ('QC1-6-214_215', u'Stort avvik mellom TAN_12 (kl.18) og TA i samme periode'),
        ('QC1-6-216', u'Stort avvik mellom TAX_12 og TA i samme periode (15 grader)'),
        ('QC1-6-217', u'Stort avvik mellom TAX_12 (kl.06) og TA i samme periode (3 grader)'),
        ('QC1-6-218', u'Stort avvik mellom TAX_12 (kl.06) og TA (kl.06) (5 grader)'),
        ('QC1-6-219', u'Stort avvik mellom TAX_12 (kl.18) og TA (kl.18) (5 grader)'),
        ('QC1-6-220', u'Stort avvik mellom TAX_12 (kl.18) og TA (kl.12) (5 grader)'),
        ('QC1-6-221', u'Stort avvik mellom TAX_12 (kl.18) og TA i samme periode'),
        ('QC1-6-224', u'Gressminimum større enn TAN_12 (kl.06)'),
        ('QC1-6-225', u'Duggpunktstemperatur større enn TA'),
        ('QC1-6-226', u'Stort avvik mellom duggpunktstemperatur og lufttemperatur (20 grader)'),
        ('QC1-6-231_232', u'Stort avvik mellom gressminimum og TAN_12'),
        ('QC1-6-233', u'TA>+5°C og snø / snøbyger (værkode)'),
        ('QC1-6-234', u'TA>+3°C og snø / snøbyger (værsymboler)'),
        ('QC1-6-235', u'TAN_12>+2°C og snø (værsymboler)'),
        ('QC1-6-236', u'Forholdet mellom temperatur og værkode (temperaturgrense -2°C)'),
        ('QC1-6-237', u'TAX_12<+0.5°C og yr / regn (værsymboler)'),
        ('QC1-6-238', u'TA<0°C og regn (værsymboler)'),
        ('QC1-6-239_242', u'Forholdet temperatur og sludd (værkode)'),
        ('QC1-6-240_243', u'Forholdet temperatur og sludd (værsymboler)'),
        ('QC1-6-241', u'TAN_12>+5°C og sludd (værsymboler)'),
        ('QC1-6-244', u'TAX_12<-2°C og sludd (værsymboler)'),
        ('QC1-6-245_246', u'Forholdet temperatur og underkjølt yr / regn (værkode, TA>0°C)'),
        ('QC1-6-247_248', u'Forholdet temperatur og underkjølt yr / regn (værkode, TA<-7°C)'),
        ('QC1-6-249', u'TA>+3°C og tåkerim (værkode)'),
        ('QC1-6-250', u'TA-TD>5 grader og tåkerim (værkode)'),
        ('QC1-6-251', u'Forholdet temperatur og værkode (Turbo-program)'),
        ('QC1-6-252', u'Forholdet temperatur og værkode (Turbo-program)'),
        ('QC1-6-253', u'Forholdet temperatur og værkode (Turbo-program)'),
        ('QC1-6-254', u'Forholdet temperatur og værkode (Turbo-program)'),
        ('QC1-6-255', u'Forholdet temperatur og værkode (Turbo-program)'),
        ('QC1-6-256', u'Forholdet temperatur og værkode (Turbo-program)'),
        ('QC1-6-257', u'Forholdet temperatur og værkode (Turbo-program)'),
        ('QC1-6-258', u'Forholdet temperatur og værkode (Turbo-program)'),
        ('QC1-6-259', u'Forholdet temperatur og isobservasjon (Turbo-program)'),
        ('QC1-6-260', u'Forholdet temperatur og isobservasjon (Turbo-program)'),
        ('QC1-6-261', u'Forholdet temperatur og isobservasjon (Turbo-program)'),
        ('QC1-6-262', u'Forholdet temperatur og isobservasjon (Turbo-program)'),
        ('QC1-6-263', u'Forholdet temperatur og isobservasjon (Turbo-program)'),
        ('QC1-6-264', u'Forholdet temperatur og isobservasjon (Turbo-program)'),
        ('QC1-6-265', u'Forholdet temperatur og isobservasjon (Turbo-program)'),
        ('QC1-6-266', u'Forholdet temperatur og isobservasjon (Turbo-program)'),
        ('QC1-6-271a', u'Stort avvik mellom FX og FF i samme periode (5 m/s)'),
        ('QC1-6-271', u'Stort avvik mellom FX og FF i samme periode (5 m/s)'),
        ('QC1-6-272', u'FG>6.5 m/s og FG>2*FX'),
        ('QC1-6-273', u'Forholdet snøfokk og vindhastighet'),
        ('QC1-6-274', u'Forholdet sjøgang og maks.middelvind'),
        ('QC1-6-275', u'Forholdet sjøgang og maks.middelvind'),
        ('QC1-6-276', u'Forholdet vindhastighet og bølgeperiode'),
        ('QC1-6-277', u'Forholdet vindhastighet og bølgeperiode / bølgehøyde'),
        ('QC1-6-278', u'Forholdet mellom bølgehøyde og bølgeperiode'),
        ('QC1-6-280', u'Forholdet vindhastighet og bølgeperiode'),
        ('QC1-6-281', u'Forholdet vindhastighet og bølgeperiode'),
        ('QC1-6-282', u'Forholdet vindhastighet og bølgeperiode'),
        ('QC1-6-283', u'Forholdet vindhastighet og bølgeperiode'),
        ('QC1-6-284', u'Forholdet vindhastighet og bølgeperiode'),
        ('QC1-6-285', u'Forholdet vindhastighet og bølgeperiode'),
        ('QC1-6-286', u'Forholdet vindhastighet og bølgeperiode'),
        ('QC1-6-287', u'PW<10 s og FF>30 m/s'),
        ('QC1-6-288', u'Forholdet mellom bølgehøyde og bølgeperiode'),
        ('QC1-6-289', u'Forholdet mellom bølgehøyde og bølgeperiode'),
        ('QC1-6-290', u'Forholdet vindhastighet og bølgehøyde'),
        ('QC1-6-291', u'Forholdet vindhastighet og bølgehøyde'),
        ('QC1-6-292', u'Forholdet vindhastighet og bølgehøyde'),
        ('QC1-6-293', u'Forholdet vindhastighet og bølgehøyde'),
        ('QC1-6-294', u'Forholdet vindhastighet og bølgehøyde'),
        ('QC1-6-295', u'Forholdet vindhastighet og bølgehøyde'),
        ('QC1-6-296', u'HW<5.0 og FF?30 m/s'),
        ('QC1-6-301', u'Islag (EM) og TGN_12>+3°C'),
        ('QC1-6-302', u'Løs og tørr snø (EM) og TGN_12>0°C'),
        ('QC1-6-305', u'Snø som fonner seg (EM) og SA<15 cm'),
        ('QC1-6-306', u'Bøtteverdi (RA) ved TA<-25'),
        ('QC1-6-307a', u'Is-lag dekker marka(EE) med varm Gressminimum(TGN>3.0)'),
        ('QC1-6-307b', u'Is-lag dekker marka(EE) med varm Gressminimum(TGN>3.0)'),
        ('QC1-6-308a', u'Tørr snø dekker marka(EE) med varm Gressminimum(TGN>0.0)'),
        ('QC1-6-308b', u'Tørr snø dekker marka(EE) med varm Gressminimum(TGN>0.0)'),
        ('QC1-6-309a', u'Snø som fonner seg(EE) med for høy eller for lav snødybde(SA<15.0||SA>150.0)'),
        ('QC1-6-309b', u'Snø som fonner seg(EE) med for høy eller for lav snødybde(SA<15.0||SA>150.0)'),
        ('QC1-6-311', u'Forholdet mellom synsvidde og værkode'),
        ('QC1-6-312', u'Forholdet mellom synsvidde og værkode'),
        ('QC1-6-313', u'Forholdet mellom synsvidde og værkode'),
        ('QC1-6-316a', u'VV<1000 m og værkode'),
        ('QC1-6-316b', u'VV<1000 m og værkode'),
        ('QC1-6-316c', u'VV<1000 m og værkode'),
        ('QC1-6-316d', u'VV<1000 m og værkode'),
        ('QC1-6-321', u'Forholdet lav skyhøyde god synsvidde'),
        ('QC1-6-322', u'Forholdet skymengde og værkode'),
        ('QC1-6-323a', u'Forholdet skymengde og værkode'),
        ('QC1-6-323b', u'Forholdet skymengde og værkode'),
        ('QC1-6-324', u'Forholdet skymengde og værkode'),
        ('QC1-6-325a', u'Forholdet skymengde og værkode'),
        ('QC1-6-325b', u'Forholdet skymengde og værkode'),
        ('QC1-6-326', u'NH=0 og nedbør (værkode)'),
        ('QC1-6-327', u'C≠9 og tordenvær (værkode)'),
        ('QC1-6-66.a', u'Forholdet mellom markas tilstand, snødybde og nedbørtype'),
        ('QC1-6-66.b_66.c', u'Forholdet mellom markas tilstand, snødybde og nedbørtype'),
        ('QC1-6-66.d', u'Forholdet mellom markas tilstand, snødybde og nedbørtype'),
        ('QC1-6-67', u'Ikke samsvar mellom endring i snødybde og TAN siste time'),
        ('QC1-6-68', u'Ikke samsvar mellom endring i snødybde og endring i bøtteverdi siste time'),
        ('QC1-7-110', u'Oppsamlet verdi over flere dager'),
        ('QC1-7-110b', u'Oppsamlet verdi over flere dager'),
        ('QC1-7-117', u'Oppsamlet verdi over flere dager'),
        ('QC1-7-248', u'Oppsamlet verdi over flere dager'),
        ('QC1-7-249', u'Oppsamlet verdi over flere dager'),

        ('QC2-redist', u'Nedbør tilfordelt i QC2, ikke oppsamlingstidspunkt'),
        ('QC2-redist-endpoint', u'Nedbør fra oppsamlingstidspunkt tilfordelt i QC2'),
        ('QC2-redist-bonedry', u'Tørt periode tilfordelt i QC2'),
        ('QC2d-1', u'Interpolert i DipTest i QC2'),
        ('QC2d-2', u'Lineær interpolasjon i QC2'),
        ('QC2d-2-I', u'Interpolasjon i QC2, basert på nabostasjoner'),
        ('QC2h-1-interruptedrain', u'Unormalt pause i en byge'),
        ('QC2h-1-highstart', u'Svært høy startverdi for en byge'),
        ('QC2h-1-highsingle', u'Svært høy enestående minuttverdi'),
        ('QC2h-1-neighbors', u'Pluviometer er tørt mens flere nabostasjoner måler nedbør, eller omvendt')
    ]
    for ce in check_explanations:
        cur.execute("INSERT INTO check_explain (qcx , description) VALUES (?, ?)", ce)
